// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

/**
 * Protobuf type {@code com.grpc.getAccountsClasses.AccountGrpc}
 */
public  final class AccountGrpc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.grpc.getAccountsClasses.AccountGrpc)
    AccountGrpcOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AccountGrpc.newBuilder() to construct.
  private AccountGrpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AccountGrpc() {
    id_ = "";
    created_ = "";
    update_ = "";
    iban_ = "";
    published_ = "";
    hidden_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AccountGrpc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            created_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            update_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            iban_ = s;
            break;
          }
          case 42: {
            com.grpc.getAccountsClasses.BalanceGRpc.Builder subBuilder = null;
            if (balance_ != null) {
              subBuilder = balance_.toBuilder();
            }
            balance_ = input.readMessage(com.grpc.getAccountsClasses.BalanceGRpc.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(balance_);
              balance_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            published_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            hidden_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.getAccountsClasses.Test.internal_static_com_grpc_getAccountsClasses_AccountGrpc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.getAccountsClasses.Test.internal_static_com_grpc_getAccountsClasses_AccountGrpc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.getAccountsClasses.AccountGrpc.class, com.grpc.getAccountsClasses.AccountGrpc.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_FIELD_NUMBER = 2;
  private volatile java.lang.Object created_;
  /**
   * <code>string created = 2;</code>
   */
  public java.lang.String getCreated() {
    java.lang.Object ref = created_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      created_ = s;
      return s;
    }
  }
  /**
   * <code>string created = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedBytes() {
    java.lang.Object ref = created_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      created_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object update_;
  /**
   * <code>string update = 3;</code>
   */
  public java.lang.String getUpdate() {
    java.lang.Object ref = update_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      update_ = s;
      return s;
    }
  }
  /**
   * <code>string update = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUpdateBytes() {
    java.lang.Object ref = update_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      update_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IBAN_FIELD_NUMBER = 4;
  private volatile java.lang.Object iban_;
  /**
   * <code>string iban = 4;</code>
   */
  public java.lang.String getIban() {
    java.lang.Object ref = iban_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iban_ = s;
      return s;
    }
  }
  /**
   * <code>string iban = 4;</code>
   */
  public com.google.protobuf.ByteString
      getIbanBytes() {
    java.lang.Object ref = iban_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iban_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BALANCE_FIELD_NUMBER = 5;
  private com.grpc.getAccountsClasses.BalanceGRpc balance_;
  /**
   * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
   */
  public boolean hasBalance() {
    return balance_ != null;
  }
  /**
   * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
   */
  public com.grpc.getAccountsClasses.BalanceGRpc getBalance() {
    return balance_ == null ? com.grpc.getAccountsClasses.BalanceGRpc.getDefaultInstance() : balance_;
  }
  /**
   * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
   */
  public com.grpc.getAccountsClasses.BalanceGRpcOrBuilder getBalanceOrBuilder() {
    return getBalance();
  }

  public static final int PUBLISHED_FIELD_NUMBER = 6;
  private volatile java.lang.Object published_;
  /**
   * <code>string published = 6;</code>
   */
  public java.lang.String getPublished() {
    java.lang.Object ref = published_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      published_ = s;
      return s;
    }
  }
  /**
   * <code>string published = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPublishedBytes() {
    java.lang.Object ref = published_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      published_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HIDDEN_FIELD_NUMBER = 7;
  private volatile java.lang.Object hidden_;
  /**
   * <code>string hidden = 7;</code>
   */
  public java.lang.String getHidden() {
    java.lang.Object ref = hidden_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hidden_ = s;
      return s;
    }
  }
  /**
   * <code>string hidden = 7;</code>
   */
  public com.google.protobuf.ByteString
      getHiddenBytes() {
    java.lang.Object ref = hidden_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hidden_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getCreatedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, created_);
    }
    if (!getUpdateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, update_);
    }
    if (!getIbanBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, iban_);
    }
    if (balance_ != null) {
      output.writeMessage(5, getBalance());
    }
    if (!getPublishedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, published_);
    }
    if (!getHiddenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, hidden_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getCreatedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, created_);
    }
    if (!getUpdateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, update_);
    }
    if (!getIbanBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, iban_);
    }
    if (balance_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getBalance());
    }
    if (!getPublishedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, published_);
    }
    if (!getHiddenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, hidden_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.getAccountsClasses.AccountGrpc)) {
      return super.equals(obj);
    }
    com.grpc.getAccountsClasses.AccountGrpc other = (com.grpc.getAccountsClasses.AccountGrpc) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getCreated()
        .equals(other.getCreated());
    result = result && getUpdate()
        .equals(other.getUpdate());
    result = result && getIban()
        .equals(other.getIban());
    result = result && (hasBalance() == other.hasBalance());
    if (hasBalance()) {
      result = result && getBalance()
          .equals(other.getBalance());
    }
    result = result && getPublished()
        .equals(other.getPublished());
    result = result && getHidden()
        .equals(other.getHidden());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CREATED_FIELD_NUMBER;
    hash = (53 * hash) + getCreated().hashCode();
    hash = (37 * hash) + UPDATE_FIELD_NUMBER;
    hash = (53 * hash) + getUpdate().hashCode();
    hash = (37 * hash) + IBAN_FIELD_NUMBER;
    hash = (53 * hash) + getIban().hashCode();
    if (hasBalance()) {
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + getBalance().hashCode();
    }
    hash = (37 * hash) + PUBLISHED_FIELD_NUMBER;
    hash = (53 * hash) + getPublished().hashCode();
    hash = (37 * hash) + HIDDEN_FIELD_NUMBER;
    hash = (53 * hash) + getHidden().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.getAccountsClasses.AccountGrpc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.getAccountsClasses.AccountGrpc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.getAccountsClasses.AccountGrpc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.getAccountsClasses.AccountGrpc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.getAccountsClasses.AccountGrpc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.getAccountsClasses.AccountGrpc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.getAccountsClasses.AccountGrpc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.getAccountsClasses.AccountGrpc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.getAccountsClasses.AccountGrpc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.getAccountsClasses.AccountGrpc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.getAccountsClasses.AccountGrpc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.getAccountsClasses.AccountGrpc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.getAccountsClasses.AccountGrpc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.grpc.getAccountsClasses.AccountGrpc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.grpc.getAccountsClasses.AccountGrpc)
      com.grpc.getAccountsClasses.AccountGrpcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.getAccountsClasses.Test.internal_static_com_grpc_getAccountsClasses_AccountGrpc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.getAccountsClasses.Test.internal_static_com_grpc_getAccountsClasses_AccountGrpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.getAccountsClasses.AccountGrpc.class, com.grpc.getAccountsClasses.AccountGrpc.Builder.class);
    }

    // Construct using com.grpc.getAccountsClasses.AccountGrpc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      created_ = "";

      update_ = "";

      iban_ = "";

      if (balanceBuilder_ == null) {
        balance_ = null;
      } else {
        balance_ = null;
        balanceBuilder_ = null;
      }
      published_ = "";

      hidden_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.getAccountsClasses.Test.internal_static_com_grpc_getAccountsClasses_AccountGrpc_descriptor;
    }

    @java.lang.Override
    public com.grpc.getAccountsClasses.AccountGrpc getDefaultInstanceForType() {
      return com.grpc.getAccountsClasses.AccountGrpc.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.getAccountsClasses.AccountGrpc build() {
      com.grpc.getAccountsClasses.AccountGrpc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.getAccountsClasses.AccountGrpc buildPartial() {
      com.grpc.getAccountsClasses.AccountGrpc result = new com.grpc.getAccountsClasses.AccountGrpc(this);
      result.id_ = id_;
      result.created_ = created_;
      result.update_ = update_;
      result.iban_ = iban_;
      if (balanceBuilder_ == null) {
        result.balance_ = balance_;
      } else {
        result.balance_ = balanceBuilder_.build();
      }
      result.published_ = published_;
      result.hidden_ = hidden_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.getAccountsClasses.AccountGrpc) {
        return mergeFrom((com.grpc.getAccountsClasses.AccountGrpc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.getAccountsClasses.AccountGrpc other) {
      if (other == com.grpc.getAccountsClasses.AccountGrpc.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getCreated().isEmpty()) {
        created_ = other.created_;
        onChanged();
      }
      if (!other.getUpdate().isEmpty()) {
        update_ = other.update_;
        onChanged();
      }
      if (!other.getIban().isEmpty()) {
        iban_ = other.iban_;
        onChanged();
      }
      if (other.hasBalance()) {
        mergeBalance(other.getBalance());
      }
      if (!other.getPublished().isEmpty()) {
        published_ = other.published_;
        onChanged();
      }
      if (!other.getHidden().isEmpty()) {
        hidden_ = other.hidden_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.getAccountsClasses.AccountGrpc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.getAccountsClasses.AccountGrpc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object created_ = "";
    /**
     * <code>string created = 2;</code>
     */
    public java.lang.String getCreated() {
      java.lang.Object ref = created_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        created_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string created = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedBytes() {
      java.lang.Object ref = created_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        created_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string created = 2;</code>
     */
    public Builder setCreated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      created_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string created = 2;</code>
     */
    public Builder clearCreated() {
      
      created_ = getDefaultInstance().getCreated();
      onChanged();
      return this;
    }
    /**
     * <code>string created = 2;</code>
     */
    public Builder setCreatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      created_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object update_ = "";
    /**
     * <code>string update = 3;</code>
     */
    public java.lang.String getUpdate() {
      java.lang.Object ref = update_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        update_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string update = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateBytes() {
      java.lang.Object ref = update_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        update_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string update = 3;</code>
     */
    public Builder setUpdate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      update_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string update = 3;</code>
     */
    public Builder clearUpdate() {
      
      update_ = getDefaultInstance().getUpdate();
      onChanged();
      return this;
    }
    /**
     * <code>string update = 3;</code>
     */
    public Builder setUpdateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      update_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object iban_ = "";
    /**
     * <code>string iban = 4;</code>
     */
    public java.lang.String getIban() {
      java.lang.Object ref = iban_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iban_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string iban = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIbanBytes() {
      java.lang.Object ref = iban_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iban_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string iban = 4;</code>
     */
    public Builder setIban(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iban_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string iban = 4;</code>
     */
    public Builder clearIban() {
      
      iban_ = getDefaultInstance().getIban();
      onChanged();
      return this;
    }
    /**
     * <code>string iban = 4;</code>
     */
    public Builder setIbanBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iban_ = value;
      onChanged();
      return this;
    }

    private com.grpc.getAccountsClasses.BalanceGRpc balance_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.getAccountsClasses.BalanceGRpc, com.grpc.getAccountsClasses.BalanceGRpc.Builder, com.grpc.getAccountsClasses.BalanceGRpcOrBuilder> balanceBuilder_;
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public boolean hasBalance() {
      return balanceBuilder_ != null || balance_ != null;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public com.grpc.getAccountsClasses.BalanceGRpc getBalance() {
      if (balanceBuilder_ == null) {
        return balance_ == null ? com.grpc.getAccountsClasses.BalanceGRpc.getDefaultInstance() : balance_;
      } else {
        return balanceBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public Builder setBalance(com.grpc.getAccountsClasses.BalanceGRpc value) {
      if (balanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        balance_ = value;
        onChanged();
      } else {
        balanceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public Builder setBalance(
        com.grpc.getAccountsClasses.BalanceGRpc.Builder builderForValue) {
      if (balanceBuilder_ == null) {
        balance_ = builderForValue.build();
        onChanged();
      } else {
        balanceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public Builder mergeBalance(com.grpc.getAccountsClasses.BalanceGRpc value) {
      if (balanceBuilder_ == null) {
        if (balance_ != null) {
          balance_ =
            com.grpc.getAccountsClasses.BalanceGRpc.newBuilder(balance_).mergeFrom(value).buildPartial();
        } else {
          balance_ = value;
        }
        onChanged();
      } else {
        balanceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public Builder clearBalance() {
      if (balanceBuilder_ == null) {
        balance_ = null;
        onChanged();
      } else {
        balance_ = null;
        balanceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public com.grpc.getAccountsClasses.BalanceGRpc.Builder getBalanceBuilder() {
      
      onChanged();
      return getBalanceFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public com.grpc.getAccountsClasses.BalanceGRpcOrBuilder getBalanceOrBuilder() {
      if (balanceBuilder_ != null) {
        return balanceBuilder_.getMessageOrBuilder();
      } else {
        return balance_ == null ?
            com.grpc.getAccountsClasses.BalanceGRpc.getDefaultInstance() : balance_;
      }
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.getAccountsClasses.BalanceGRpc, com.grpc.getAccountsClasses.BalanceGRpc.Builder, com.grpc.getAccountsClasses.BalanceGRpcOrBuilder> 
        getBalanceFieldBuilder() {
      if (balanceBuilder_ == null) {
        balanceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.getAccountsClasses.BalanceGRpc, com.grpc.getAccountsClasses.BalanceGRpc.Builder, com.grpc.getAccountsClasses.BalanceGRpcOrBuilder>(
                getBalance(),
                getParentForChildren(),
                isClean());
        balance_ = null;
      }
      return balanceBuilder_;
    }

    private java.lang.Object published_ = "";
    /**
     * <code>string published = 6;</code>
     */
    public java.lang.String getPublished() {
      java.lang.Object ref = published_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        published_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string published = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPublishedBytes() {
      java.lang.Object ref = published_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        published_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string published = 6;</code>
     */
    public Builder setPublished(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      published_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string published = 6;</code>
     */
    public Builder clearPublished() {
      
      published_ = getDefaultInstance().getPublished();
      onChanged();
      return this;
    }
    /**
     * <code>string published = 6;</code>
     */
    public Builder setPublishedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      published_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object hidden_ = "";
    /**
     * <code>string hidden = 7;</code>
     */
    public java.lang.String getHidden() {
      java.lang.Object ref = hidden_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hidden_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hidden = 7;</code>
     */
    public com.google.protobuf.ByteString
        getHiddenBytes() {
      java.lang.Object ref = hidden_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hidden_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hidden = 7;</code>
     */
    public Builder setHidden(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hidden_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hidden = 7;</code>
     */
    public Builder clearHidden() {
      
      hidden_ = getDefaultInstance().getHidden();
      onChanged();
      return this;
    }
    /**
     * <code>string hidden = 7;</code>
     */
    public Builder setHiddenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hidden_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.grpc.getAccountsClasses.AccountGrpc)
  }

  // @@protoc_insertion_point(class_scope:com.grpc.getAccountsClasses.AccountGrpc)
  private static final com.grpc.getAccountsClasses.AccountGrpc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.getAccountsClasses.AccountGrpc();
  }

  public static com.grpc.getAccountsClasses.AccountGrpc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AccountGrpc>
      PARSER = new com.google.protobuf.AbstractParser<AccountGrpc>() {
    @java.lang.Override
    public AccountGrpc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AccountGrpc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AccountGrpc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AccountGrpc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.getAccountsClasses.AccountGrpc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

