// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface accountsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.accountsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.grpc.getAccountsClasses.AccountGrpc accounts = 1;</code>
   */
  java.util.List<com.grpc.getAccountsClasses.AccountGrpc> 
      getAccountsList();
  /**
   * <code>repeated .com.grpc.getAccountsClasses.AccountGrpc accounts = 1;</code>
   */
  com.grpc.getAccountsClasses.AccountGrpc getAccounts(int index);
  /**
   * <code>repeated .com.grpc.getAccountsClasses.AccountGrpc accounts = 1;</code>
   */
  int getAccountsCount();
  /**
   * <code>repeated .com.grpc.getAccountsClasses.AccountGrpc accounts = 1;</code>
   */
  java.util.List<? extends com.grpc.getAccountsClasses.AccountGrpcOrBuilder> 
      getAccountsOrBuilderList();
  /**
   * <code>repeated .com.grpc.getAccountsClasses.AccountGrpc accounts = 1;</code>
   */
  com.grpc.getAccountsClasses.AccountGrpcOrBuilder getAccountsOrBuilder(
      int index);
}
