// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface AccountGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.AccountGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string created = 2;</code>
   */
  java.lang.String getCreated();
  /**
   * <code>string created = 2;</code>
   */
  com.google.protobuf.ByteString
      getCreatedBytes();

  /**
   * <code>string update = 3;</code>
   */
  java.lang.String getUpdate();
  /**
   * <code>string update = 3;</code>
   */
  com.google.protobuf.ByteString
      getUpdateBytes();

  /**
   * <code>string iban = 4;</code>
   */
  java.lang.String getIban();
  /**
   * <code>string iban = 4;</code>
   */
  com.google.protobuf.ByteString
      getIbanBytes();

  /**
   * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
   */
  boolean hasBalance();
  /**
   * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
   */
  com.grpc.getAccountsClasses.BalanceGRpc getBalance();
  /**
   * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
   */
  com.grpc.getAccountsClasses.BalanceGRpcOrBuilder getBalanceOrBuilder();

  /**
   * <code>string published = 6;</code>
   */
  java.lang.String getPublished();
  /**
   * <code>string published = 6;</code>
   */
  com.google.protobuf.ByteString
      getPublishedBytes();

  /**
   * <code>string hidden = 7;</code>
   */
  java.lang.String getHidden();
  /**
   * <code>string hidden = 7;</code>
   */
  com.google.protobuf.ByteString
      getHiddenBytes();
}
