// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface addTurnoverRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.addTurnoverRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.grpc.getAccountsClasses.TurnoverGrpc account = 1;</code>
   */
  boolean hasAccount();
  /**
   * <code>.com.grpc.getAccountsClasses.TurnoverGrpc account = 1;</code>
   */
  com.grpc.getAccountsClasses.TurnoverGrpc getAccount();
  /**
   * <code>.com.grpc.getAccountsClasses.TurnoverGrpc account = 1;</code>
   */
  com.grpc.getAccountsClasses.TurnoverGrpcOrBuilder getAccountOrBuilder();
}
