// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface addTurnoverResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.addTurnoverResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool b = 1;</code>
   */
  boolean getB();
}
