// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface BalanceGRpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.BalanceGRpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>string precision = 2;</code>
   */
  java.lang.String getPrecision();
  /**
   * <code>string precision = 2;</code>
   */
  com.google.protobuf.ByteString
      getPrecisionBytes();

  /**
   * <code>string currency = 3;</code>
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 3;</code>
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();
}
