// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface findAccountByIbanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.findAccountByIbanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.grpc.getAccountsClasses.AccountGrpc account = 1;</code>
   */
  boolean hasAccount();
  /**
   * <code>.com.grpc.getAccountsClasses.AccountGrpc account = 1;</code>
   */
  com.grpc.getAccountsClasses.AccountGrpc getAccount();
  /**
   * <code>.com.grpc.getAccountsClasses.AccountGrpc account = 1;</code>
   */
  com.grpc.getAccountsClasses.AccountGrpcOrBuilder getAccountOrBuilder();
}
