// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface findTurnoverByIbanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.findTurnoverByIbanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.grpc.getAccountsClasses.TurnoverGrpc account = 1;</code>
   */
  java.util.List<com.grpc.getAccountsClasses.TurnoverGrpc> 
      getAccountList();
  /**
   * <code>repeated .com.grpc.getAccountsClasses.TurnoverGrpc account = 1;</code>
   */
  com.grpc.getAccountsClasses.TurnoverGrpc getAccount(int index);
  /**
   * <code>repeated .com.grpc.getAccountsClasses.TurnoverGrpc account = 1;</code>
   */
  int getAccountCount();
  /**
   * <code>repeated .com.grpc.getAccountsClasses.TurnoverGrpc account = 1;</code>
   */
  java.util.List<? extends com.grpc.getAccountsClasses.TurnoverGrpcOrBuilder> 
      getAccountOrBuilderList();
  /**
   * <code>repeated .com.grpc.getAccountsClasses.TurnoverGrpc account = 1;</code>
   */
  com.grpc.getAccountsClasses.TurnoverGrpcOrBuilder getAccountOrBuilder(
      int index);
}
