// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface removeTurnoverRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.removeTurnoverRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string s = 1;</code>
   */
  java.lang.String getS();
  /**
   * <code>string s = 1;</code>
   */
  com.google.protobuf.ByteString
      getSBytes();
}
