// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_BalanceGRpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_BalanceGRpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_AccountGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_AccountGrpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_removeAccountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_removeAccountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_removeAccountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_removeAccountResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_findAccountByIbanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_findAccountByIbanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_findAccountByIbanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_findAccountByIbanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_addAccountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_addAccountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_addAccountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_addAccountResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_updateAccountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_updateAccountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_updateAccountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_updateAccountResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_accountsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_accountsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_accountsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_accountsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_AmountGRpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_AmountGRpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_TurnoverGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_TurnoverGrpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_removeTurnoverRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_removeTurnoverRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_removeTurnoverResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_removeTurnoverResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_findTurnoverByIbanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_findTurnoverByIbanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_findTurnoverByIbanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_findTurnoverByIbanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_addTurnoverRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_addTurnoverRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_addTurnoverResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_addTurnoverResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_updateTurnoverRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_updateTurnoverRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_updateTurnoverResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_updateTurnoverResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_turnoversRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_turnoversRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_getAccountsClasses_turnoversResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_getAccountsClasses_turnoversResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\033com.grpc.getAccountsClasse" +
      "s\"A\n\013BalanceGRpc\022\r\n\005value\030\001 \001(\t\022\021\n\tpreci" +
      "sion\030\002 \001(\t\022\020\n\010currency\030\003 \001(\t\"\246\001\n\013Account" +
      "Grpc\022\n\n\002id\030\001 \001(\t\022\017\n\007created\030\002 \001(\t\022\016\n\006upd" +
      "ate\030\003 \001(\t\022\014\n\004iban\030\004 \001(\t\0229\n\007balance\030\005 \001(\013" +
      "2(.com.grpc.getAccountsClasses.BalanceGR" +
      "pc\022\021\n\tpublished\030\006 \001(\t\022\016\n\006hidden\030\007 \001(\t\"!\n" +
      "\024removeAccountRequest\022\t\n\001s\030\001 \001(\t\"\027\n\025remo" +
      "veAccountResponse\"%\n\030findAccountByIbanRe" +
      "quest\022\t\n\001s\030\001 \001(\t\"V\n\031findAccountByIbanRes" +
      "ponse\0229\n\007account\030\001 \001(\0132(.com.grpc.getAcc" +
      "ountsClasses.AccountGrpc\"N\n\021addAccountRe" +
      "quest\0229\n\007account\030\001 \001(\0132(.com.grpc.getAcc" +
      "ountsClasses.AccountGrpc\"\037\n\022addAccountRe" +
      "sponse\022\t\n\001b\030\001 \001(\010\"Q\n\024updateAccountReques" +
      "t\0229\n\007account\030\001 \001(\0132(.com.grpc.getAccount" +
      "sClasses.AccountGrpc\"\027\n\025updateAccountRes" +
      "ponse\"\021\n\017accountsRequest\"N\n\020accountsResp" +
      "onse\022:\n\010accounts\030\001 \003(\0132(.com.grpc.getAcc" +
      "ountsClasses.AccountGrpc\"@\n\nAmountGRpc\022\r" +
      "\n\005value\030\001 \001(\t\022\021\n\tprecision\030\002 \001(\t\022\020\n\010curr" +
      "ency\030\003 \001(\t\"\216\002\n\014TurnoverGrpc\022\022\n\nturnoverI" +
      "d\030\001 \001(\t\022\023\n\013accountIban\030\002 \001(\t\022\032\n\022counterA" +
      "ccountName\030\003 \001(\t\0227\n\006amount\030\004 \001(\0132\'.com.g" +
      "rpc.getAccountsClasses.AmountGRpc\0229\n\007bal" +
      "ance\030\005 \001(\0132(.com.grpc.getAccountsClasses" +
      ".BalanceGRpc\022\014\n\004note\030\006 \001(\t\022\023\n\013descriptio" +
      "n\030\007 \001(\t\022\020\n\010specific\030\010 \001(\t\022\020\n\010variable\030\t " +
      "\001(\t\"\"\n\025removeTurnoverRequest\022\t\n\001s\030\001 \001(\t\"" +
      "\030\n\026removeTurnoverResponse\"&\n\031findTurnove" +
      "rByIbanRequest\022\t\n\001s\030\001 \001(\t\"X\n\032findTurnove" +
      "rByIbanResponse\022:\n\007account\030\001 \003(\0132).com.g" +
      "rpc.getAccountsClasses.TurnoverGrpc\"P\n\022a" +
      "ddTurnoverRequest\022:\n\007account\030\001 \001(\0132).com" +
      ".grpc.getAccountsClasses.TurnoverGrpc\" \n" +
      "\023addTurnoverResponse\022\t\n\001b\030\001 \001(\010\"S\n\025updat" +
      "eTurnoverRequest\022:\n\007account\030\001 \003(\0132).com." +
      "grpc.getAccountsClasses.TurnoverGrpc\"\030\n\026" +
      "updateTurnoverResponse\"\022\n\020turnoversReque" +
      "st\"P\n\021turnoversResponse\022;\n\010accounts\030\001 \003(" +
      "\0132).com.grpc.getAccountsClasses.Turnover" +
      "Grpc2\335\004\n\016AccountService\022v\n\rremoveAccount" +
      "\0221.com.grpc.getAccountsClasses.removeAcc" +
      "ountRequest\0322.com.grpc.getAccountsClasse" +
      "s.removeAccountResponse\022\202\001\n\021findAccountB" +
      "yIban\0225.com.grpc.getAccountsClasses.find" +
      "AccountByIbanRequest\0326.com.grpc.getAccou" +
      "ntsClasses.findAccountByIbanResponse\022m\n\n" +
      "addAccount\022..com.grpc.getAccountsClasses" +
      ".addAccountRequest\032/.com.grpc.getAccount" +
      "sClasses.addAccountResponse\022v\n\rupdateAcc" +
      "ount\0221.com.grpc.getAccountsClasses.updat" +
      "eAccountRequest\0322.com.grpc.getAccountsCl" +
      "asses.updateAccountResponse\022g\n\010accounts\022" +
      ",.com.grpc.getAccountsClasses.accountsRe" +
      "quest\032-.com.grpc.getAccountsClasses.acco" +
      "untsResponse2\355\004\n\017TurnoverService\022y\n\016remo" +
      "veTurnover\0222.com.grpc.getAccountsClasses" +
      ".removeTurnoverRequest\0323.com.grpc.getAcc" +
      "ountsClasses.removeTurnoverResponse\022\205\001\n\022" +
      "findTurnoverByIban\0226.com.grpc.getAccount" +
      "sClasses.findTurnoverByIbanRequest\0327.com" +
      ".grpc.getAccountsClasses.findTurnoverByI" +
      "banResponse\022p\n\013addTurnover\022/.com.grpc.ge" +
      "tAccountsClasses.addTurnoverRequest\0320.co" +
      "m.grpc.getAccountsClasses.addTurnoverRes" +
      "ponse\022y\n\016updateTurnover\0222.com.grpc.getAc" +
      "countsClasses.updateTurnoverRequest\0323.co" +
      "m.grpc.getAccountsClasses.updateTurnover" +
      "Response\022j\n\tturnovers\022-.com.grpc.getAcco" +
      "untsClasses.turnoversRequest\032..com.grpc." +
      "getAccountsClasses.turnoversResponseB\002P\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_grpc_getAccountsClasses_BalanceGRpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpc_getAccountsClasses_BalanceGRpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_BalanceGRpc_descriptor,
        new java.lang.String[] { "Value", "Precision", "Currency", });
    internal_static_com_grpc_getAccountsClasses_AccountGrpc_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpc_getAccountsClasses_AccountGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_AccountGrpc_descriptor,
        new java.lang.String[] { "Id", "Created", "Update", "Iban", "Balance", "Published", "Hidden", });
    internal_static_com_grpc_getAccountsClasses_removeAccountRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_grpc_getAccountsClasses_removeAccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_removeAccountRequest_descriptor,
        new java.lang.String[] { "S", });
    internal_static_com_grpc_getAccountsClasses_removeAccountResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_grpc_getAccountsClasses_removeAccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_removeAccountResponse_descriptor,
        new java.lang.String[] { });
    internal_static_com_grpc_getAccountsClasses_findAccountByIbanRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_grpc_getAccountsClasses_findAccountByIbanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_findAccountByIbanRequest_descriptor,
        new java.lang.String[] { "S", });
    internal_static_com_grpc_getAccountsClasses_findAccountByIbanResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_grpc_getAccountsClasses_findAccountByIbanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_findAccountByIbanResponse_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_com_grpc_getAccountsClasses_addAccountRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_grpc_getAccountsClasses_addAccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_addAccountRequest_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_com_grpc_getAccountsClasses_addAccountResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_grpc_getAccountsClasses_addAccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_addAccountResponse_descriptor,
        new java.lang.String[] { "B", });
    internal_static_com_grpc_getAccountsClasses_updateAccountRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_grpc_getAccountsClasses_updateAccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_updateAccountRequest_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_com_grpc_getAccountsClasses_updateAccountResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_grpc_getAccountsClasses_updateAccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_updateAccountResponse_descriptor,
        new java.lang.String[] { });
    internal_static_com_grpc_getAccountsClasses_accountsRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_grpc_getAccountsClasses_accountsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_accountsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_grpc_getAccountsClasses_accountsResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_grpc_getAccountsClasses_accountsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_accountsResponse_descriptor,
        new java.lang.String[] { "Accounts", });
    internal_static_com_grpc_getAccountsClasses_AmountGRpc_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_grpc_getAccountsClasses_AmountGRpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_AmountGRpc_descriptor,
        new java.lang.String[] { "Value", "Precision", "Currency", });
    internal_static_com_grpc_getAccountsClasses_TurnoverGrpc_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_grpc_getAccountsClasses_TurnoverGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_TurnoverGrpc_descriptor,
        new java.lang.String[] { "TurnoverId", "AccountIban", "CounterAccountName", "Amount", "Balance", "Note", "Description", "Specific", "Variable", });
    internal_static_com_grpc_getAccountsClasses_removeTurnoverRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_grpc_getAccountsClasses_removeTurnoverRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_removeTurnoverRequest_descriptor,
        new java.lang.String[] { "S", });
    internal_static_com_grpc_getAccountsClasses_removeTurnoverResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_grpc_getAccountsClasses_removeTurnoverResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_removeTurnoverResponse_descriptor,
        new java.lang.String[] { });
    internal_static_com_grpc_getAccountsClasses_findTurnoverByIbanRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_grpc_getAccountsClasses_findTurnoverByIbanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_findTurnoverByIbanRequest_descriptor,
        new java.lang.String[] { "S", });
    internal_static_com_grpc_getAccountsClasses_findTurnoverByIbanResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_grpc_getAccountsClasses_findTurnoverByIbanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_findTurnoverByIbanResponse_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_com_grpc_getAccountsClasses_addTurnoverRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_grpc_getAccountsClasses_addTurnoverRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_addTurnoverRequest_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_com_grpc_getAccountsClasses_addTurnoverResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_grpc_getAccountsClasses_addTurnoverResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_addTurnoverResponse_descriptor,
        new java.lang.String[] { "B", });
    internal_static_com_grpc_getAccountsClasses_updateTurnoverRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_grpc_getAccountsClasses_updateTurnoverRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_updateTurnoverRequest_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_com_grpc_getAccountsClasses_updateTurnoverResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_grpc_getAccountsClasses_updateTurnoverResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_updateTurnoverResponse_descriptor,
        new java.lang.String[] { });
    internal_static_com_grpc_getAccountsClasses_turnoversRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_grpc_getAccountsClasses_turnoversRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_turnoversRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_grpc_getAccountsClasses_turnoversResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_grpc_getAccountsClasses_turnoversResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_getAccountsClasses_turnoversResponse_descriptor,
        new java.lang.String[] { "Accounts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
