// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

/**
 * Protobuf type {@code com.grpc.getAccountsClasses.TurnoverGrpc}
 */
public  final class TurnoverGrpc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.grpc.getAccountsClasses.TurnoverGrpc)
    TurnoverGrpcOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TurnoverGrpc.newBuilder() to construct.
  private TurnoverGrpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TurnoverGrpc() {
    turnoverId_ = "";
    accountIban_ = "";
    counterAccountName_ = "";
    note_ = "";
    description_ = "";
    specific_ = "";
    variable_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TurnoverGrpc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            turnoverId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            accountIban_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            counterAccountName_ = s;
            break;
          }
          case 34: {
            com.grpc.getAccountsClasses.AmountGRpc.Builder subBuilder = null;
            if (amount_ != null) {
              subBuilder = amount_.toBuilder();
            }
            amount_ = input.readMessage(com.grpc.getAccountsClasses.AmountGRpc.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(amount_);
              amount_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.grpc.getAccountsClasses.BalanceGRpc.Builder subBuilder = null;
            if (balance_ != null) {
              subBuilder = balance_.toBuilder();
            }
            balance_ = input.readMessage(com.grpc.getAccountsClasses.BalanceGRpc.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(balance_);
              balance_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            note_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            specific_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            variable_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.getAccountsClasses.Test.internal_static_com_grpc_getAccountsClasses_TurnoverGrpc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.getAccountsClasses.Test.internal_static_com_grpc_getAccountsClasses_TurnoverGrpc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.getAccountsClasses.TurnoverGrpc.class, com.grpc.getAccountsClasses.TurnoverGrpc.Builder.class);
  }

  public static final int TURNOVERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object turnoverId_;
  /**
   * <code>string turnoverId = 1;</code>
   */
  public java.lang.String getTurnoverId() {
    java.lang.Object ref = turnoverId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      turnoverId_ = s;
      return s;
    }
  }
  /**
   * <code>string turnoverId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTurnoverIdBytes() {
    java.lang.Object ref = turnoverId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      turnoverId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNTIBAN_FIELD_NUMBER = 2;
  private volatile java.lang.Object accountIban_;
  /**
   * <code>string accountIban = 2;</code>
   */
  public java.lang.String getAccountIban() {
    java.lang.Object ref = accountIban_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountIban_ = s;
      return s;
    }
  }
  /**
   * <code>string accountIban = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAccountIbanBytes() {
    java.lang.Object ref = accountIban_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountIban_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNTERACCOUNTNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object counterAccountName_;
  /**
   * <code>string counterAccountName = 3;</code>
   */
  public java.lang.String getCounterAccountName() {
    java.lang.Object ref = counterAccountName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      counterAccountName_ = s;
      return s;
    }
  }
  /**
   * <code>string counterAccountName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCounterAccountNameBytes() {
    java.lang.Object ref = counterAccountName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      counterAccountName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 4;
  private com.grpc.getAccountsClasses.AmountGRpc amount_;
  /**
   * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
   */
  public boolean hasAmount() {
    return amount_ != null;
  }
  /**
   * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
   */
  public com.grpc.getAccountsClasses.AmountGRpc getAmount() {
    return amount_ == null ? com.grpc.getAccountsClasses.AmountGRpc.getDefaultInstance() : amount_;
  }
  /**
   * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
   */
  public com.grpc.getAccountsClasses.AmountGRpcOrBuilder getAmountOrBuilder() {
    return getAmount();
  }

  public static final int BALANCE_FIELD_NUMBER = 5;
  private com.grpc.getAccountsClasses.BalanceGRpc balance_;
  /**
   * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
   */
  public boolean hasBalance() {
    return balance_ != null;
  }
  /**
   * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
   */
  public com.grpc.getAccountsClasses.BalanceGRpc getBalance() {
    return balance_ == null ? com.grpc.getAccountsClasses.BalanceGRpc.getDefaultInstance() : balance_;
  }
  /**
   * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
   */
  public com.grpc.getAccountsClasses.BalanceGRpcOrBuilder getBalanceOrBuilder() {
    return getBalance();
  }

  public static final int NOTE_FIELD_NUMBER = 6;
  private volatile java.lang.Object note_;
  /**
   * <code>string note = 6;</code>
   */
  public java.lang.String getNote() {
    java.lang.Object ref = note_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      note_ = s;
      return s;
    }
  }
  /**
   * <code>string note = 6;</code>
   */
  public com.google.protobuf.ByteString
      getNoteBytes() {
    java.lang.Object ref = note_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      note_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 7;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 7;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 7;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPECIFIC_FIELD_NUMBER = 8;
  private volatile java.lang.Object specific_;
  /**
   * <code>string specific = 8;</code>
   */
  public java.lang.String getSpecific() {
    java.lang.Object ref = specific_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      specific_ = s;
      return s;
    }
  }
  /**
   * <code>string specific = 8;</code>
   */
  public com.google.protobuf.ByteString
      getSpecificBytes() {
    java.lang.Object ref = specific_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      specific_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VARIABLE_FIELD_NUMBER = 9;
  private volatile java.lang.Object variable_;
  /**
   * <code>string variable = 9;</code>
   */
  public java.lang.String getVariable() {
    java.lang.Object ref = variable_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      variable_ = s;
      return s;
    }
  }
  /**
   * <code>string variable = 9;</code>
   */
  public com.google.protobuf.ByteString
      getVariableBytes() {
    java.lang.Object ref = variable_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      variable_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTurnoverIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, turnoverId_);
    }
    if (!getAccountIbanBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accountIban_);
    }
    if (!getCounterAccountNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, counterAccountName_);
    }
    if (amount_ != null) {
      output.writeMessage(4, getAmount());
    }
    if (balance_ != null) {
      output.writeMessage(5, getBalance());
    }
    if (!getNoteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, note_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, description_);
    }
    if (!getSpecificBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, specific_);
    }
    if (!getVariableBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, variable_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTurnoverIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, turnoverId_);
    }
    if (!getAccountIbanBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accountIban_);
    }
    if (!getCounterAccountNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, counterAccountName_);
    }
    if (amount_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getAmount());
    }
    if (balance_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getBalance());
    }
    if (!getNoteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, note_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, description_);
    }
    if (!getSpecificBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, specific_);
    }
    if (!getVariableBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, variable_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.getAccountsClasses.TurnoverGrpc)) {
      return super.equals(obj);
    }
    com.grpc.getAccountsClasses.TurnoverGrpc other = (com.grpc.getAccountsClasses.TurnoverGrpc) obj;

    boolean result = true;
    result = result && getTurnoverId()
        .equals(other.getTurnoverId());
    result = result && getAccountIban()
        .equals(other.getAccountIban());
    result = result && getCounterAccountName()
        .equals(other.getCounterAccountName());
    result = result && (hasAmount() == other.hasAmount());
    if (hasAmount()) {
      result = result && getAmount()
          .equals(other.getAmount());
    }
    result = result && (hasBalance() == other.hasBalance());
    if (hasBalance()) {
      result = result && getBalance()
          .equals(other.getBalance());
    }
    result = result && getNote()
        .equals(other.getNote());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && getSpecific()
        .equals(other.getSpecific());
    result = result && getVariable()
        .equals(other.getVariable());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TURNOVERID_FIELD_NUMBER;
    hash = (53 * hash) + getTurnoverId().hashCode();
    hash = (37 * hash) + ACCOUNTIBAN_FIELD_NUMBER;
    hash = (53 * hash) + getAccountIban().hashCode();
    hash = (37 * hash) + COUNTERACCOUNTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCounterAccountName().hashCode();
    if (hasAmount()) {
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount().hashCode();
    }
    if (hasBalance()) {
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + getBalance().hashCode();
    }
    hash = (37 * hash) + NOTE_FIELD_NUMBER;
    hash = (53 * hash) + getNote().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + SPECIFIC_FIELD_NUMBER;
    hash = (53 * hash) + getSpecific().hashCode();
    hash = (37 * hash) + VARIABLE_FIELD_NUMBER;
    hash = (53 * hash) + getVariable().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.getAccountsClasses.TurnoverGrpc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.getAccountsClasses.TurnoverGrpc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.getAccountsClasses.TurnoverGrpc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.getAccountsClasses.TurnoverGrpc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.getAccountsClasses.TurnoverGrpc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.getAccountsClasses.TurnoverGrpc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.getAccountsClasses.TurnoverGrpc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.getAccountsClasses.TurnoverGrpc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.getAccountsClasses.TurnoverGrpc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.getAccountsClasses.TurnoverGrpc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.getAccountsClasses.TurnoverGrpc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.getAccountsClasses.TurnoverGrpc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.getAccountsClasses.TurnoverGrpc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.grpc.getAccountsClasses.TurnoverGrpc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.grpc.getAccountsClasses.TurnoverGrpc)
      com.grpc.getAccountsClasses.TurnoverGrpcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.getAccountsClasses.Test.internal_static_com_grpc_getAccountsClasses_TurnoverGrpc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.getAccountsClasses.Test.internal_static_com_grpc_getAccountsClasses_TurnoverGrpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.getAccountsClasses.TurnoverGrpc.class, com.grpc.getAccountsClasses.TurnoverGrpc.Builder.class);
    }

    // Construct using com.grpc.getAccountsClasses.TurnoverGrpc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      turnoverId_ = "";

      accountIban_ = "";

      counterAccountName_ = "";

      if (amountBuilder_ == null) {
        amount_ = null;
      } else {
        amount_ = null;
        amountBuilder_ = null;
      }
      if (balanceBuilder_ == null) {
        balance_ = null;
      } else {
        balance_ = null;
        balanceBuilder_ = null;
      }
      note_ = "";

      description_ = "";

      specific_ = "";

      variable_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.getAccountsClasses.Test.internal_static_com_grpc_getAccountsClasses_TurnoverGrpc_descriptor;
    }

    @java.lang.Override
    public com.grpc.getAccountsClasses.TurnoverGrpc getDefaultInstanceForType() {
      return com.grpc.getAccountsClasses.TurnoverGrpc.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.getAccountsClasses.TurnoverGrpc build() {
      com.grpc.getAccountsClasses.TurnoverGrpc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.getAccountsClasses.TurnoverGrpc buildPartial() {
      com.grpc.getAccountsClasses.TurnoverGrpc result = new com.grpc.getAccountsClasses.TurnoverGrpc(this);
      result.turnoverId_ = turnoverId_;
      result.accountIban_ = accountIban_;
      result.counterAccountName_ = counterAccountName_;
      if (amountBuilder_ == null) {
        result.amount_ = amount_;
      } else {
        result.amount_ = amountBuilder_.build();
      }
      if (balanceBuilder_ == null) {
        result.balance_ = balance_;
      } else {
        result.balance_ = balanceBuilder_.build();
      }
      result.note_ = note_;
      result.description_ = description_;
      result.specific_ = specific_;
      result.variable_ = variable_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.getAccountsClasses.TurnoverGrpc) {
        return mergeFrom((com.grpc.getAccountsClasses.TurnoverGrpc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.getAccountsClasses.TurnoverGrpc other) {
      if (other == com.grpc.getAccountsClasses.TurnoverGrpc.getDefaultInstance()) return this;
      if (!other.getTurnoverId().isEmpty()) {
        turnoverId_ = other.turnoverId_;
        onChanged();
      }
      if (!other.getAccountIban().isEmpty()) {
        accountIban_ = other.accountIban_;
        onChanged();
      }
      if (!other.getCounterAccountName().isEmpty()) {
        counterAccountName_ = other.counterAccountName_;
        onChanged();
      }
      if (other.hasAmount()) {
        mergeAmount(other.getAmount());
      }
      if (other.hasBalance()) {
        mergeBalance(other.getBalance());
      }
      if (!other.getNote().isEmpty()) {
        note_ = other.note_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getSpecific().isEmpty()) {
        specific_ = other.specific_;
        onChanged();
      }
      if (!other.getVariable().isEmpty()) {
        variable_ = other.variable_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.getAccountsClasses.TurnoverGrpc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.getAccountsClasses.TurnoverGrpc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object turnoverId_ = "";
    /**
     * <code>string turnoverId = 1;</code>
     */
    public java.lang.String getTurnoverId() {
      java.lang.Object ref = turnoverId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        turnoverId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string turnoverId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTurnoverIdBytes() {
      java.lang.Object ref = turnoverId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        turnoverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string turnoverId = 1;</code>
     */
    public Builder setTurnoverId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      turnoverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string turnoverId = 1;</code>
     */
    public Builder clearTurnoverId() {
      
      turnoverId_ = getDefaultInstance().getTurnoverId();
      onChanged();
      return this;
    }
    /**
     * <code>string turnoverId = 1;</code>
     */
    public Builder setTurnoverIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      turnoverId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object accountIban_ = "";
    /**
     * <code>string accountIban = 2;</code>
     */
    public java.lang.String getAccountIban() {
      java.lang.Object ref = accountIban_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountIban_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accountIban = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountIbanBytes() {
      java.lang.Object ref = accountIban_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountIban_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accountIban = 2;</code>
     */
    public Builder setAccountIban(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountIban_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string accountIban = 2;</code>
     */
    public Builder clearAccountIban() {
      
      accountIban_ = getDefaultInstance().getAccountIban();
      onChanged();
      return this;
    }
    /**
     * <code>string accountIban = 2;</code>
     */
    public Builder setAccountIbanBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountIban_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object counterAccountName_ = "";
    /**
     * <code>string counterAccountName = 3;</code>
     */
    public java.lang.String getCounterAccountName() {
      java.lang.Object ref = counterAccountName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        counterAccountName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string counterAccountName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCounterAccountNameBytes() {
      java.lang.Object ref = counterAccountName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        counterAccountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string counterAccountName = 3;</code>
     */
    public Builder setCounterAccountName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      counterAccountName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string counterAccountName = 3;</code>
     */
    public Builder clearCounterAccountName() {
      
      counterAccountName_ = getDefaultInstance().getCounterAccountName();
      onChanged();
      return this;
    }
    /**
     * <code>string counterAccountName = 3;</code>
     */
    public Builder setCounterAccountNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      counterAccountName_ = value;
      onChanged();
      return this;
    }

    private com.grpc.getAccountsClasses.AmountGRpc amount_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.getAccountsClasses.AmountGRpc, com.grpc.getAccountsClasses.AmountGRpc.Builder, com.grpc.getAccountsClasses.AmountGRpcOrBuilder> amountBuilder_;
    /**
     * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
     */
    public boolean hasAmount() {
      return amountBuilder_ != null || amount_ != null;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
     */
    public com.grpc.getAccountsClasses.AmountGRpc getAmount() {
      if (amountBuilder_ == null) {
        return amount_ == null ? com.grpc.getAccountsClasses.AmountGRpc.getDefaultInstance() : amount_;
      } else {
        return amountBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
     */
    public Builder setAmount(com.grpc.getAccountsClasses.AmountGRpc value) {
      if (amountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        amount_ = value;
        onChanged();
      } else {
        amountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
     */
    public Builder setAmount(
        com.grpc.getAccountsClasses.AmountGRpc.Builder builderForValue) {
      if (amountBuilder_ == null) {
        amount_ = builderForValue.build();
        onChanged();
      } else {
        amountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
     */
    public Builder mergeAmount(com.grpc.getAccountsClasses.AmountGRpc value) {
      if (amountBuilder_ == null) {
        if (amount_ != null) {
          amount_ =
            com.grpc.getAccountsClasses.AmountGRpc.newBuilder(amount_).mergeFrom(value).buildPartial();
        } else {
          amount_ = value;
        }
        onChanged();
      } else {
        amountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
     */
    public Builder clearAmount() {
      if (amountBuilder_ == null) {
        amount_ = null;
        onChanged();
      } else {
        amount_ = null;
        amountBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
     */
    public com.grpc.getAccountsClasses.AmountGRpc.Builder getAmountBuilder() {
      
      onChanged();
      return getAmountFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
     */
    public com.grpc.getAccountsClasses.AmountGRpcOrBuilder getAmountOrBuilder() {
      if (amountBuilder_ != null) {
        return amountBuilder_.getMessageOrBuilder();
      } else {
        return amount_ == null ?
            com.grpc.getAccountsClasses.AmountGRpc.getDefaultInstance() : amount_;
      }
    }
    /**
     * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.getAccountsClasses.AmountGRpc, com.grpc.getAccountsClasses.AmountGRpc.Builder, com.grpc.getAccountsClasses.AmountGRpcOrBuilder> 
        getAmountFieldBuilder() {
      if (amountBuilder_ == null) {
        amountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.getAccountsClasses.AmountGRpc, com.grpc.getAccountsClasses.AmountGRpc.Builder, com.grpc.getAccountsClasses.AmountGRpcOrBuilder>(
                getAmount(),
                getParentForChildren(),
                isClean());
        amount_ = null;
      }
      return amountBuilder_;
    }

    private com.grpc.getAccountsClasses.BalanceGRpc balance_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.getAccountsClasses.BalanceGRpc, com.grpc.getAccountsClasses.BalanceGRpc.Builder, com.grpc.getAccountsClasses.BalanceGRpcOrBuilder> balanceBuilder_;
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public boolean hasBalance() {
      return balanceBuilder_ != null || balance_ != null;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public com.grpc.getAccountsClasses.BalanceGRpc getBalance() {
      if (balanceBuilder_ == null) {
        return balance_ == null ? com.grpc.getAccountsClasses.BalanceGRpc.getDefaultInstance() : balance_;
      } else {
        return balanceBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public Builder setBalance(com.grpc.getAccountsClasses.BalanceGRpc value) {
      if (balanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        balance_ = value;
        onChanged();
      } else {
        balanceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public Builder setBalance(
        com.grpc.getAccountsClasses.BalanceGRpc.Builder builderForValue) {
      if (balanceBuilder_ == null) {
        balance_ = builderForValue.build();
        onChanged();
      } else {
        balanceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public Builder mergeBalance(com.grpc.getAccountsClasses.BalanceGRpc value) {
      if (balanceBuilder_ == null) {
        if (balance_ != null) {
          balance_ =
            com.grpc.getAccountsClasses.BalanceGRpc.newBuilder(balance_).mergeFrom(value).buildPartial();
        } else {
          balance_ = value;
        }
        onChanged();
      } else {
        balanceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public Builder clearBalance() {
      if (balanceBuilder_ == null) {
        balance_ = null;
        onChanged();
      } else {
        balance_ = null;
        balanceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public com.grpc.getAccountsClasses.BalanceGRpc.Builder getBalanceBuilder() {
      
      onChanged();
      return getBalanceFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    public com.grpc.getAccountsClasses.BalanceGRpcOrBuilder getBalanceOrBuilder() {
      if (balanceBuilder_ != null) {
        return balanceBuilder_.getMessageOrBuilder();
      } else {
        return balance_ == null ?
            com.grpc.getAccountsClasses.BalanceGRpc.getDefaultInstance() : balance_;
      }
    }
    /**
     * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.getAccountsClasses.BalanceGRpc, com.grpc.getAccountsClasses.BalanceGRpc.Builder, com.grpc.getAccountsClasses.BalanceGRpcOrBuilder> 
        getBalanceFieldBuilder() {
      if (balanceBuilder_ == null) {
        balanceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.getAccountsClasses.BalanceGRpc, com.grpc.getAccountsClasses.BalanceGRpc.Builder, com.grpc.getAccountsClasses.BalanceGRpcOrBuilder>(
                getBalance(),
                getParentForChildren(),
                isClean());
        balance_ = null;
      }
      return balanceBuilder_;
    }

    private java.lang.Object note_ = "";
    /**
     * <code>string note = 6;</code>
     */
    public java.lang.String getNote() {
      java.lang.Object ref = note_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        note_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string note = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNoteBytes() {
      java.lang.Object ref = note_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        note_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string note = 6;</code>
     */
    public Builder setNote(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      note_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string note = 6;</code>
     */
    public Builder clearNote() {
      
      note_ = getDefaultInstance().getNote();
      onChanged();
      return this;
    }
    /**
     * <code>string note = 6;</code>
     */
    public Builder setNoteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      note_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 7;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 7;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 7;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 7;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object specific_ = "";
    /**
     * <code>string specific = 8;</code>
     */
    public java.lang.String getSpecific() {
      java.lang.Object ref = specific_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        specific_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string specific = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSpecificBytes() {
      java.lang.Object ref = specific_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        specific_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string specific = 8;</code>
     */
    public Builder setSpecific(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      specific_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string specific = 8;</code>
     */
    public Builder clearSpecific() {
      
      specific_ = getDefaultInstance().getSpecific();
      onChanged();
      return this;
    }
    /**
     * <code>string specific = 8;</code>
     */
    public Builder setSpecificBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      specific_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object variable_ = "";
    /**
     * <code>string variable = 9;</code>
     */
    public java.lang.String getVariable() {
      java.lang.Object ref = variable_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        variable_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string variable = 9;</code>
     */
    public com.google.protobuf.ByteString
        getVariableBytes() {
      java.lang.Object ref = variable_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        variable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string variable = 9;</code>
     */
    public Builder setVariable(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      variable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string variable = 9;</code>
     */
    public Builder clearVariable() {
      
      variable_ = getDefaultInstance().getVariable();
      onChanged();
      return this;
    }
    /**
     * <code>string variable = 9;</code>
     */
    public Builder setVariableBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      variable_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.grpc.getAccountsClasses.TurnoverGrpc)
  }

  // @@protoc_insertion_point(class_scope:com.grpc.getAccountsClasses.TurnoverGrpc)
  private static final com.grpc.getAccountsClasses.TurnoverGrpc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.getAccountsClasses.TurnoverGrpc();
  }

  public static com.grpc.getAccountsClasses.TurnoverGrpc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TurnoverGrpc>
      PARSER = new com.google.protobuf.AbstractParser<TurnoverGrpc>() {
    @java.lang.Override
    public TurnoverGrpc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TurnoverGrpc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TurnoverGrpc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TurnoverGrpc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.getAccountsClasses.TurnoverGrpc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

