// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface turnoversResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.turnoversResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.grpc.getAccountsClasses.TurnoverGrpc accounts = 1;</code>
   */
  java.util.List<com.grpc.getAccountsClasses.TurnoverGrpc> 
      getAccountsList();
  /**
   * <code>repeated .com.grpc.getAccountsClasses.TurnoverGrpc accounts = 1;</code>
   */
  com.grpc.getAccountsClasses.TurnoverGrpc getAccounts(int index);
  /**
   * <code>repeated .com.grpc.getAccountsClasses.TurnoverGrpc accounts = 1;</code>
   */
  int getAccountsCount();
  /**
   * <code>repeated .com.grpc.getAccountsClasses.TurnoverGrpc accounts = 1;</code>
   */
  java.util.List<? extends com.grpc.getAccountsClasses.TurnoverGrpcOrBuilder> 
      getAccountsOrBuilderList();
  /**
   * <code>repeated .com.grpc.getAccountsClasses.TurnoverGrpc accounts = 1;</code>
   */
  com.grpc.getAccountsClasses.TurnoverGrpcOrBuilder getAccountsOrBuilder(
      int index);
}
