// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface TurnoverGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.TurnoverGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string turnoverId = 1;</code>
   */
  java.lang.String getTurnoverId();
  /**
   * <code>string turnoverId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTurnoverIdBytes();

  /**
   * <code>string accountIban = 2;</code>
   */
  java.lang.String getAccountIban();
  /**
   * <code>string accountIban = 2;</code>
   */
  com.google.protobuf.ByteString
      getAccountIbanBytes();

  /**
   * <code>string counterAccountName = 3;</code>
   */
  java.lang.String getCounterAccountName();
  /**
   * <code>string counterAccountName = 3;</code>
   */
  com.google.protobuf.ByteString
      getCounterAccountNameBytes();

  /**
   * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
   */
  boolean hasAmount();
  /**
   * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
   */
  com.grpc.getAccountsClasses.AmountGRpc getAmount();
  /**
   * <code>.com.grpc.getAccountsClasses.AmountGRpc amount = 4;</code>
   */
  com.grpc.getAccountsClasses.AmountGRpcOrBuilder getAmountOrBuilder();

  /**
   * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
   */
  boolean hasBalance();
  /**
   * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
   */
  com.grpc.getAccountsClasses.BalanceGRpc getBalance();
  /**
   * <code>.com.grpc.getAccountsClasses.BalanceGRpc balance = 5;</code>
   */
  com.grpc.getAccountsClasses.BalanceGRpcOrBuilder getBalanceOrBuilder();

  /**
   * <code>string note = 6;</code>
   */
  java.lang.String getNote();
  /**
   * <code>string note = 6;</code>
   */
  com.google.protobuf.ByteString
      getNoteBytes();

  /**
   * <code>string description = 7;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 7;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string specific = 8;</code>
   */
  java.lang.String getSpecific();
  /**
   * <code>string specific = 8;</code>
   */
  com.google.protobuf.ByteString
      getSpecificBytes();

  /**
   * <code>string variable = 9;</code>
   */
  java.lang.String getVariable();
  /**
   * <code>string variable = 9;</code>
   */
  com.google.protobuf.ByteString
      getVariableBytes();
}
