// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface turnoversRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.turnoversRequest)
    com.google.protobuf.MessageOrBuilder {
}
