// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface updateAccountRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.updateAccountRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.grpc.getAccountsClasses.AccountGrpc account = 1;</code>
   */
  boolean hasAccount();
  /**
   * <code>.com.grpc.getAccountsClasses.AccountGrpc account = 1;</code>
   */
  com.grpc.getAccountsClasses.AccountGrpc getAccount();
  /**
   * <code>.com.grpc.getAccountsClasses.AccountGrpc account = 1;</code>
   */
  com.grpc.getAccountsClasses.AccountGrpcOrBuilder getAccountOrBuilder();
}
