// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.grpc.getAccountsClasses;

public interface updateAccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.getAccountsClasses.updateAccountResponse)
    com.google.protobuf.MessageOrBuilder {
}
